// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PairCode.ConceitosBasicos.Presentations.Web.MVC.Infrastructures.Data;

#nullable disable

namespace PairCode.ConceitosBasicos.Presentations.Web.MVC.Infrastructures.Data.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("default")
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTest.Web.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(32)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Username")
                        .HasColumnType("VARCHAR(64)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIOS", "default");
                });
#pragma warning restore 612, 618
        }
    }
}
